server:
  port: 8060

management:
  security:
    enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: bus-client
  kafka:
    host: localhost
    port: 5672
    username: user
    password: secret
  cloud:
    bus:
      trace:
        enabled: true

