server:
  port: 8050

spring:
  application:
    name: bus-client-2
  kafka:
    host: localhost
    port: 5672
    username: user
    password: secret

management:
  security:
    enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


